rules:
  1:
    title: '&f&l1 Общие правила'
    strings:
      - '1.1 Начиная игру на Minecraft сервере DreamTime, Вы соглашаетесь с данным сводом правил.
         1.2 Незнание правил не освобождает Вас от ответственности.
         1.3 Администрация оставляет за собой право не уведомлять игроков об изменении данных правил.
         1.4 На данный момент в составе Высшей Администрации находится SteveGrKek.
         1.5 Высшая Администрация оставляет за собой право выдавать наказание игрокам без веской причины.
         1.6 Запрещается копировать и выдавать за свой данный свод правил без согласия обоих членов Высшей Администрации.
         (Наказание: Вечный бан на всём проекте)
         1.7 Запрещается использовать в никнейме, плаще и/или скине:
         - Нецензурные выражения (маты), оскорбления, унижения;
         - Рекламу других проектов (Даже если они не относятся к Minecraft);
         - Намеки на то, что Вы являетесь Командой сервера, если на самом деле не так.
         (Наказание: Вечный бан)
         1.8 Запрещается распространение вредоносного контента и программного обеспечения.
         (Наказание: Вечный бан)
         1.9 Запрещено провоцировать людей на нарушение правил сервера.
         (Наказание: Бан от 1 дня)
         1.10 Запрещено передавать аккаунт третьим лицам.
         (Наказание: Вечный бан на всём проекте)
         1.11 Ответственность несёт владелец аккаунта, независимо от того, кто совершал действия.'
      - 'str2'
      - 'str3'
      - 'str4'
      - 'str5'
      - 'str6'
  2:
    title: 'title2'
    strings:
      - 'str7'
      - 'str8'
      - 'str9'
      - 'str10'
      - 'str11'
      - 'str12'